# Generated by Django 4.2.2 on 2023-08-05 18:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userName', models.CharField(max_length=100, unique=True, verbose_name='nombre de Usuario')),
                ('email', models.EmailField(max_length=25, unique=True, verbose_name='Correo Electronico')),
                ('nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos')),
                ('perfil', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objeto', django.db.models.manager.Manager()),
            ],
        ),
    ]
